artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: LRP_Study_A
model: InteractionGNN

# Dataset parameters
datatype_split: [1000, 100, 10] # Number of [training, validation, testing] examples
num_tracks: 20
track_dis_width: 10
num_layer: 10
min_r: 0.1
max_r: 0.5
detector_width: 0.5
ptcut: 0.0
eff: 1.0
pur: 0.01

# Model parameters
edge_cut: 0.5
spatial_channels: 2
cell_channels: 0
hidden: 64
n_graph_iters: 4
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: True
aggregation: sum_max
hidden_activation: SiLU
weight: 1
warmup: 10
lr: 0.007
factor: 0.8
train_purity: 0
patience: 50
truth_key: y
mask_background: False
max_epochs: 200