# Data params
input_dir: /global/cfs/cdirs/m3443/data/JetTagging/top_tagging/processed_input_pyg/
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: LRP_JetTagging_Study_B
model: GravNet_jet
gpus: 1
nodes: 1

# Dataset parameters
data_split: [400000,40000,40000]
feature_set: [pE, py, px, pz, delta_eta, log_delta_E, delta_phi, log_pt, log_E, log_delta_pt, delta_pt, delta_E, delta_R,
              jet_pt, jet_mass, jet_phi, jet_eta, jet_pE, jet_px, jet_py, jet_pz]


# Training params
max_epochs: 400
lr: 0.003
factor: 0.8
patience: 100
warmup: 10
train_batch: 800
val_batch: 800
dropout: 0.1
signal_goal: 0.3 # The efficiency goal for the signal jets

# Model params
edge_cut: 0.5
spatial_channels:
hidden: 128
n_graph_iters: 3
nb_node_layer: 3
nb_edge_layer: 3
layernorm: True
batchnorm: True
aggregation: mean_sum
hidden_activation: SiLU
output_activation: 
graph_construction: 

# GravNet-specific parameters
knn:  # If knn_start_end not set, then the number of neighbors in each GravNet conv
rand_k: 

r: 0.1
max_knn: 30

emb_dims: 64
grav_weight: 2.0
grav_level: 0 # 
norm: False

learned_grav_weight: False
grav_activation: 